mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: wallet_<%= Rails.env %>

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *mysql

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults